/* Signal Workshop: pure conversion primitives stay framework-agnostic so pages, tests, and future API surfaces share one source of truth. */
export type Unit = { id: string; label: string; symbol: string; factor?: number; offset?: number };
export type Converter = { slug: string; from: Unit; to: Unit; category: string; title: string; description: string; formula: string; convert: (n:number)=>number; inverse: (n:number)=>number };

const U = (id:string,label:string,symbol:string,factor:number,offset=0):Unit => ({id,label,symbol,factor,offset});
export const sets: Record<string, Unit[]> = {
  length:[U('m','Meters','m',1),U('ft','Feet','ft',.3048),U('in','Inches','in',.0254),U('cm','Centimeters','cm',.01),U('km','Kilometers','km',1000),U('mi','Miles','mi',1609.344)],
  weight:[U('kg','Kilograms','kg',1),U('lb','Pounds','lb',.45359237),U('g','Grams','g',.001),U('oz','Ounces','oz',.0283495231)],
  temperature:[U('c','Celsius','°C',1),U('f','Fahrenheit','°F',1),U('k','Kelvin','K',1)],
  area:[U('sqm','Square meters','m²',1),U('sqft','Square feet','ft²',.09290304),U('acre','Acres','ac',4046.8564224)],
  volume:[U('l','Liters','L',1),U('gal','Gallons','gal',3.785411784),U('ml','Milliliters','mL',.001),U('floz','Fluid ounces','fl oz',.0295735296)],
  speed:[U('kmh','Kilometers / hour','km/h',1),U('mph','Miles / hour','mph',1.609344)],
  time:[U('sec','Seconds','s',1),U('min','Minutes','min',60),U('hr','Hours','h',3600),U('day','Days','d',86400)],
  data:[U('byte','Bytes','B',1),U('kb','Kilobytes','KB',1024),U('mb','Megabytes','MB',1024**2),U('gb','Gigabytes','GB',1024**3),U('tb','Terabytes','TB',1024**4)],
};
export const names:Record<string,string> = {length:'Length',weight:'Weight',temperature:'Temperature',area:'Area',volume:'Volume',speed:'Speed',time:'Time',data:'Data'};
export function temp(n:number,from:string,to:string){ const c=from==='c'?n:from==='f'?(n-32)*5/9:n-273.15; return to==='c'?c:to==='f'?c*9/5+32:c+273.15; }
function make(slug:string,from:Unit,to:Unit,category:string):Converter { const isTemp=category==='temperature'; const fn=(n:number)=>isTemp?temp(n,from.id,to.id):n*(from.factor??1)/(to.factor??1); const inv=(n:number)=>isTemp?temp(n,to.id,from.id):n*(to.factor??1)/(from.factor??1); return {slug,from,to,category,title:`${from.label} to ${to.label} Converter`,description:`Convert ${from.label.toLowerCase()} to ${to.label.toLowerCase()} instantly with a precise, browser-local converter.`,formula:isTemp?`${from.symbol} → ${to.symbol} uses the standard temperature offset formula.`:`1 ${from.label.slice(0,-1).toLowerCase()} = ${(1/(to.factor??1)*(from.factor??1)).toFixed(6)} ${to.label.toLowerCase()}.`,convert:fn,inverse:inv}; }
export const converters:Converter[] = [make('meters-to-feet',sets.length[0],sets.length[1],'length'),make('feet-to-meters',sets.length[1],sets.length[0],'length'),make('inches-to-centimeters',sets.length[2],sets.length[3],'length'),make('centimeters-to-inches',sets.length[3],sets.length[2],'length'),make('kilometers-to-miles',sets.length[4],sets.length[5],'length'),make('miles-to-kilometers',sets.length[5],sets.length[4],'length'),make('kg-to-lbs',sets.weight[0],sets.weight[1],'weight'),make('lbs-to-kg',sets.weight[1],sets.weight[0],'weight'),make('grams-to-ounces',sets.weight[2],sets.weight[3],'weight'),make('ounces-to-grams',sets.weight[3],sets.weight[2],'weight'),make('celsius-to-fahrenheit',sets.temperature[0],sets.temperature[1],'temperature'),make('fahrenheit-to-celsius',sets.temperature[1],sets.temperature[0],'temperature'),make('celsius-to-kelvin',sets.temperature[0],sets.temperature[2],'temperature'),make('square-meters-to-square-feet',sets.area[0],sets.area[1],'area'),make('square-feet-to-square-meters',sets.area[1],sets.area[0],'area'),make('acres-to-square-meters',sets.area[2],sets.area[0],'area'),make('liters-to-gallons',sets.volume[0],sets.volume[1],'volume'),make('gallons-to-liters',sets.volume[1],sets.volume[0],'volume'),make('milliliters-to-ounces',sets.volume[2],sets.volume[3],'volume'),make('kmh-to-mph',sets.speed[0],sets.speed[1],'speed'),make('mph-to-kmh',sets.speed[1],sets.speed[0],'speed'),make('seconds-to-minutes',sets.time[0],sets.time[1],'time'),make('minutes-to-hours',sets.time[1],sets.time[2],'time'),make('hours-to-days',sets.time[2],sets.time[3],'time'),make('bytes-to-kb',sets.data[0],sets.data[1],'data'),make('mb-to-gb',sets.data[2],sets.data[3],'data'),make('gb-to-tb',sets.data[3],sets.data[4],'data')];
export const precisionOptions = ['Auto','2 decimals','4 decimals','6 decimals','8 decimals'];
export function formatNumber(value:number, precision:string){ if(!Number.isFinite(value)) return '—'; if(precision==='Auto') return Math.abs(value)>=1000?value.toLocaleString('en-US',{maximumFractionDigits:6}):String(Number(value.toFixed(6))); return value.toFixed(Number(precision.split(' ')[0])); }
export function find(slug?:string){ return converters.find(c=>c.slug===slug) ?? converters[0]; }
