/* Signal Workshop: format transformations are deterministic pure functions with explicit failure strings for the UI layer. */
export function csvEscape(value: unknown) { const text=String(value??''); return /[",\n]/.test(text) ? `"${text.replace(/"/g,'""')}"` : text; }
export function jsonToCsv(input: any) { const rows=Array.isArray(input)?input:[input]; const keys=Array.from(new Set(rows.flatMap((r:any)=>Object.keys(r||{})))); return [keys.join(','),...rows.map((r:any)=>keys.map(k=>csvEscape(typeof r?.[k]==='object'?JSON.stringify(r[k]):r?.[k])).join(','))].join('\n'); }
export function csvToJson(text:string) { const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean); if(!lines.length)return []; const parse=(line:string)=>{const out:string[]=[];let cur='',quote=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){cur+='"';i++;}else if(c==='"')quote=!quote;else if(c===','&&!quote){out.push(cur);cur='';}else cur+=c;}out.push(cur);return out}; const headers=parse(lines[0]); return lines.slice(1).map(line=>{const values=parse(line);return Object.fromEntries(headers.map((h,i)=>[h,values[i]??'']))}); }
export function escapeXml(s:string){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');}
export function jsonToXml(value:any,key='root'):string { if(Array.isArray(value))return value.map(v=>jsonToXml(v,key)).join(''); if(value&&typeof value==='object')return `<${key}>${Object.entries(value).map(([k,v])=>jsonToXml(v,k)).join('')}</${key}>`; return `<${key}>${escapeXml(String(value??''))}</${key}>`; }
export function base64Encode(input:string){ if(typeof btoa!=='undefined'){const bytes=new TextEncoder().encode(input);let binary='';bytes.forEach(byte=>binary+=String.fromCharCode(byte));return btoa(binary)} return Buffer.from(input,'utf8').toString('base64'); }
export function base64Decode(input:string){ if(typeof atob!=='undefined'){const binary=atob(input);const bytes=Uint8Array.from(binary,c=>c.charCodeAt(0));return new TextDecoder().decode(bytes)} return Buffer.from(input,'base64').toString('utf8'); }
export function executeFormat(type:string,input:string) { try { if(type==='json-formatter')return JSON.stringify(JSON.parse(input),null,2); if(type==='json-validator'){JSON.parse(input);return 'Valid JSON';} if(type==='json-minifier')return JSON.stringify(JSON.parse(input)); if(type==='json-to-csv')return jsonToCsv(JSON.parse(input)); if(type==='csv-to-json')return JSON.stringify(csvToJson(input),null,2); if(type==='json-to-xml')return jsonToXml(JSON.parse(input)); if(type==='base64-encoder')return base64Encode(input); if(type==='base64-decoder')return base64Decode(input); if(type==='url-encoder')return encodeURIComponent(input); if(type==='url-decoder')return decodeURIComponent(input); if(type==='unix-timestamp-converter'){const n=Number(input);return Number.isFinite(n)?new Date(n<1e12?n*1000:n).toISOString():'Invalid timestamp';} return input; } catch { return type==='json-validator'?'Invalid JSON — check commas, quotes, and brackets.':'Could not process this input. Check the format and try again.'; } }
