/* Signal Workshop: content pages use editorial rails, numbered metadata, and useful pathways back to the instruments. */
import { Link } from 'wouter';
import { ArrowRight, ChevronRight } from 'lucide-react';
import SEO from '../components/SEO';

const categoryData:Record<string,{title:string;description:string;units:string;popular:[string,string][]}> = {
 length:{title:'Length converters',description:'Move between metric and imperial length units with precise, browser-local calculations.',units:'meters · feet · inches · centimeters · kilometers · miles',popular:[['/meters-to-feet','Meters to Feet'],['/feet-to-meters','Feet to Meters'],['/converters/length','Length converter']]},
 weight:{title:'Weight converters',description:'Convert everyday mass and weight measurements for recipes, shipping, fitness, and engineering work.',units:'kilograms · pounds · grams · ounces',popular:[['/kg-to-lbs','Kilograms to Pounds'],['/lbs-to-kg','Pounds to Kilograms'],['/converters/weight','Weight converter']]},
 temperature:{title:'Temperature converters',description:'Convert Celsius, Fahrenheit, and Kelvin with offset-aware formulas rather than simple factors.',units:'Celsius · Fahrenheit · Kelvin',popular:[['/celsius-to-fahrenheit','Celsius to Fahrenheit'],['/converters/temperature','Temperature converter']]},
 area:{title:'Area converters',description:'Translate surfaces and land measurements between square units and acres.',units:'square meters · square feet · acres',popular:[['/converters/area','Area converter']]},
 volume:{title:'Volume converters',description:'Convert liquids and capacity measurements across liters, gallons, milliliters, and fluid ounces.',units:'liters · gallons · milliliters · fluid ounces',popular:[['/liters-to-gallons','Liters to Gallons'],['/converters/volume','Volume converter']]},
 speed:{title:'Speed converters',description:'Compare kilometers per hour and miles per hour with live precision controls.',units:'km/h · mph',popular:[['/converters/speed','Speed converter']]},
 time:{title:'Time converters',description:'Move between seconds, minutes, hours, and days without leaving the browser.',units:'seconds · minutes · hours · days',popular:[['/converters/time','Time converter']]},
 data:{title:'Data storage converters',description:'Translate bytes and binary storage units for file sizes, downloads, and technical documentation.',units:'bytes · KB · MB · GB · TB',popular:[['/converters/data','Data converter']]},
};
export function CategoryPage({category}:{category:string}){const data=categoryData[category]??categoryData.length; const faq=[{question:`What units does the ${data.title.toLowerCase()} page support?`,answer:`This page is configured for ${data.units}. Each pair uses a real conversion formula and updates in the browser.`},{question:'Are inputs uploaded?',answer:'No. Ordinary conversions are processed locally in your browser whenever possible.'}]; return <main className="container py-14"><SEO title={`${data.title} | ConvertKit`} description={data.description} faq={faq} breadcrumbs={[{name:'Home',url:'/'},{name:'Unit converters',url:'/converters'},{name:data.title,url:`/converters/${category}`}]}/><div className="grid gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-end"><div><p className="signal-rule font-mono text-[10px] uppercase tracking-[.18em] text-[#356ae6]">Unit catalog / {category}</p><h1 className="mt-5 font-display text-5xl font-bold tracking-[-.05em]">{data.title}</h1><p className="mt-5 max-w-xl text-lg leading-7 text-[#647087]">{data.description}</p></div><div className="bg-[#111827] p-6 text-white shadow-[10px_10px_0_#dbe1eb]"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[#9fb7ff]">Supported units</p><p className="mt-5 font-mono text-sm leading-7 text-[#dbe7ff]">{data.units}</p><p className="mt-6 border-t border-[#34445e] pt-4 text-xs text-[#91a0b6]">Live results · local processing · adjustable precision</p></div></div><div className="mt-14 grid gap-10 lg:grid-cols-[1.2fr_.8fr]"><div><h2 className="signal-rule font-display text-2xl font-bold">Popular conversions</h2><div className="mt-5 grid gap-3">{data.popular.map(([href,label],i)=><Link key={href} href={href} className="flex items-center justify-between border-b border-[#dbe1eb] bg-white px-5 py-5 transition hover:pl-7 hover:text-[#356ae6]"><span><span className="mr-4 font-mono text-[10px] text-[#356ae6]">0{i+1}</span>{label}</span><ArrowRight size={16}/></Link>)}</div></div><div><h2 className="signal-rule font-display text-2xl font-bold">FAQ</h2><div className="mt-5 grid gap-5">{faq.map(item=><div key={item.question}><h3 className="font-semibold">{item.question}</h3><p className="mt-2 text-sm leading-6 text-[#647087]">{item.answer}</p></div>)}</div></div></div><div className="mt-14 border-t border-[#dbe1eb] pt-8"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[#356ae6]">Related categories</p><div className="mt-5 flex flex-wrap gap-2">{Object.entries(categoryData).filter(([key])=>key!==category).slice(0,5).map(([key,value])=><Link key={key} href={`/converters/${key}`} className="flex items-center gap-2 border border-[#dbe1eb] bg-white px-4 py-3 text-sm hover:border-[#356ae6]">{value.title.replace(' converters','')}<ChevronRight size={14} className="text-[#356ae6]"/></Link>)}</div></div></main>}

const articles=[['/blog/meters-to-feet','How to Convert Meters to Feet','Length','A practical explanation of the meter-to-foot factor, with examples and a live converter.','/meters-to-feet'],['/blog/kilograms-to-pounds','How to Convert Kilograms to Pounds','Weight','Understand the kilogram-to-pound relationship and choose useful precision.','/kg-to-lbs'],['/blog/celsius-to-fahrenheit','How to Convert Celsius to Fahrenheit','Temperature','Why temperature needs an offset formula, not just a factor.','/celsius-to-fahrenheit'],['/blog/liters-to-gallons','How to Convert Liters to Gallons','Volume','A clear guide to liquid volume conversions for everyday use.','/liters-to-gallons'],['/blog/format-json','How to Format JSON','Developer','Readable JSON is easier to inspect, validate, and share.','/json-formatter'],['/blog/json-to-csv','How to Convert JSON to CSV','Format','How to preserve headers, quotes, commas, and nested values.','/json-to-csv'],['/blog/unix-timestamp','What Is a Unix Timestamp','Developer','Understand seconds, milliseconds, UTC, local time, and ISO 8601.','/unix-timestamp-converter']];
export function BlogPage(){return <main className="container py-14"><SEO title="Conversion Guides | ConvertKit" description="Practical guides for unit conversions, JSON formatting, CSV conversion, Base64, and Unix timestamps." type="Article" breadcrumbs={[{name:'Home',url:'/'},{name:'Guides',url:'/blog'}]}/><div className="max-w-2xl"><p className="signal-rule font-mono text-[10px] uppercase tracking-[.18em] text-[#356ae6]">Field notes / 03</p><h1 className="mt-5 font-display text-5xl font-bold tracking-[-.05em]">Guides for getting<br/><span className="text-[#356ae6]">the conversion right.</span></h1><p className="mt-5 text-lg leading-7 text-[#647087]">Short, practical notes connected to the tools you can use immediately.</p></div><div className="mt-14 grid gap-px border border-[#cdd5e2] bg-[#cdd5e2] md:grid-cols-2">{articles.map(([href,title,category,desc,tool],i)=><article key={href} className="bg-[#f7f8fb] p-6 transition hover:bg-white"><div className="flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-[.14em] text-[#356ae6]">{String(i+1).padStart(2,'0')} / {category}</span><ChevronRight size={15} className="text-[#9aa7ba]"/></div><h2 className="mt-9 font-display text-2xl font-bold">{title}</h2><p className="mt-3 text-sm leading-6 text-[#647087]">{desc}</p><div className="mt-7 flex flex-wrap gap-4 text-sm font-semibold"><Link href={href} className="text-[#172033] hover:text-[#356ae6]">Read guide <ArrowRight size={14} className="ml-1 inline"/></Link><Link href={tool} className="text-[#356ae6]">Open tool</Link></div></article>)}</div></main>}

export function BlogArticle({slug}:{slug:string}){const article=articles.find(item=>item[0].split('/').pop()===slug)??articles[0]; return <main className="container py-14"><SEO title={`${article[1]} | ConvertKit`} description={article[3]} type="Article" breadcrumbs={[{name:'Home',url:'/'},{name:'Guides',url:'/blog'},{name:article[1],url:article[0]}]}/><div className="mx-auto max-w-3xl"><p className="signal-rule font-mono text-[10px] uppercase tracking-[.18em] text-[#356ae6]">{article[2]} / field note</p><h1 className="mt-6 font-display text-5xl font-bold leading-[1.04] tracking-[-.05em]">{article[1]}</h1><p className="mt-6 text-xl leading-8 text-[#647087]">{article[3]}</p><div className="mt-12 border-l-2 border-[#356ae6] bg-white p-6"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[#356ae6]">The useful answer</p><p className="mt-4 leading-8 text-[#172033]">Use the linked ConvertKit tool to test real values immediately. The calculator keeps your input in the browser whenever possible and shows the formula alongside the result.</p></div><div className="prose prose-slate mt-12 max-w-none"><h2>Start with the relationship</h2><p>Conversions are easier to trust when the source unit, target unit, factor, and precision are visible. ConvertKit presents those details together instead of hiding them behind a single opaque result.</p><h2>Check the result with examples</h2><p>Try small values, round values, and a value from your actual task. Comparing the table with the live result helps catch wrong unit selections before you copy the answer elsewhere.</p><h2>Use the tool</h2><p>When you are ready, open the dedicated converter and use the swap, reset, precision, and copy controls to finish the task.</p></div><Link href={article[4]} className="mt-10 inline-flex items-center gap-2 bg-[#356ae6] px-5 py-3 text-sm font-semibold text-white hover:bg-[#244db7]">Open {article[2]} tool <ArrowRight size={15}/></Link></div></main>}
